In [11]:
import gym
import numpy as np

env = gym.make('FrozenLake-v1')

ns = env.observation_space.n
na = env.action_space.n
Q = np.zeros((ns, na))

ep = 1000
spe = 100
alpha = 0.1
y = 0.99
E = 1.0
max_E = 1.0
min_E = 0.01
E_decay = 0.001


for episode in range(ep):
    s = env.reset()
    done = False

    for step in range(spe):
        exploration_threshold = np.random.uniform(0, 1)
        if exploration_threshold > E:
            a = np.argmax(Q[s, :])
        else:
            a = env.action_space.sample()

        s1, r, done, _ = env.step(a)

        Q[s, a] = (1 - alpha) * Q[s, a] + alpha * (r + y * np.max(Q[s1, :]))

        s = s1

        if done:
            break

    E = min_E + \
                       (max_E - min_E) * np.exp(-E_decay * episode)

print("Learned Q-table:")
print(Q)

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)
/usr/local/lib/python3.10/dist-packages/gym/core.py:317: DeprecationWarning: WARN: Initializing wrapper in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  deprecation(
/usr/local/lib/python3.10/dist-packages/gym/wrappers/step_api_compatibility.py:39: DeprecationWarning: WARN: Initializing environment in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  deprecation(


Learned Q-table:
[[0.26503501 0.24079939 0.25507534 0.22355982]
 [0.12282238 0.11320978 0.08484027 0.17821273]
 [0.15415254 0.09617729 0.08287225 0.0724749 ]
 [0.04759319 0.01975511 0.01069747 0.01975086]
 [0.2744705  0.1233381  0.17348221 0.13372919]
 [0.         0.         0.         0.        ]
 [0.13128658 0.03453577 0.07783269 0.00739285]
 [0.         0.         0.         0.        ]
 [0.17406452 0.16471276 0.18274955 0.28406599]
 [0.16106233 0.30210323 0.1438224  0.18036534]
 [0.28199533 0.23031926 0.19201759 0.13530784]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.19780377 0.26318793 0.37796404 0.19606153]
 [0.15299422 0.33492663 0.35130933 0.49658738]
 [0.         0.         0.         0.        ]]
