In [5]:
import numpy as np

w = 4
h = 4
na = 4

ep = 1000
spe = 100
alpha = 0.1
y = 0.99
E = 0.1

Q = np.zeros((w, h, na))

def epsilon_greedy(s, E):
    if np.random.uniform() < E:
        a = np.random.randint(na)
    else:
        a = np.argmax(Q[s[0], s[1], :])
    return a


for episode in range(ep):
    s = (0, 0)  # Start state
    a = epsilon_greedy(s, E)

    for step in range(spe):
        if a == 0:
            s1 = (s[0], max(s[1] - 1, 0))
        elif a == 1:
            s1 = (s[0], min(s[1] + 1, h - 1))
        elif a == 2:
            s1 = (max(s[0] - 1, 0), s[1])
        else:
            s1 = (min(s[0] + 1, w - 1), s[1])

        r = -1

        a1 = epsilon_greedy(s1, E)

        Q[s[0], s[1], a] += alpha * (r + y * Q[s1[0], s1[1], a1] - Q[s[0], s[1], a])

        s = s1
        a = a1

        if s == (w - 1, h - 1):
            break

print("Optimal Q-values:")
print(Q)

Optimal Q-values:
[[[-6.99569155 -6.1653007  -6.85327504 -6.04434358]
  [-6.09561361 -5.17112676 -5.60441876 -5.21134399]
  [-5.13798967 -4.16398053 -4.37901857 -4.08901964]
  [-3.73321459 -3.3744685  -3.3956001  -3.22928907]]

 [[-5.67245381 -5.14031036 -6.11724969 -5.11694262]
  [-5.37893741 -4.19746097 -4.68914998 -4.17801622]
  [-4.26195295 -3.04806226 -3.85343142 -3.21080451]
  [-3.56080976 -2.85813131 -3.14189454 -2.13025714]]

 [[-4.45602901 -4.21880023 -4.69280184 -4.11010756]
  [-4.21017006 -3.1529681  -4.45343547 -3.25184615]
  [-3.69078535 -2.05457568 -2.82078214 -2.35367232]
  [-2.83707858 -1.69402648 -2.63673445 -1.        ]]

 [[-3.31220627 -3.15554696 -3.83958082 -3.40546491]
  [-2.91610219 -2.23173359 -3.19180361 -2.47352598]
  [-2.64912203 -1.         -2.66973992 -1.81877111]
  [ 0.          0.          0.          0.        ]]]
